default: [example/default_config.yml, example/default_config.yml]
name: mnist
runner: example/mnist_runner.py

train:
  lr: "Lambda(lambda epoch: 0.001 * 0.95**epoch, epochwise=True)"
  use_fp16: true
