#!/bin/bash

tzq () {
    cmd=$(python -m torchzq.cli $@)
    bash -c "$cmd"
}

case "$1" in
    *.y*ml)
        tzq "$@"
        ;;
    *)
        echo "Error: Unknown command: \"$1\"."
        ;;
esac
