#!/bin/bash

set -e

parse_yaml () {
    cat $1 | sed '/^runner/d' | sed 's/#.+$//g' | sed -r '/^\s*$/d' | sed -e 's/^/--/' | sed -e 's/://'
}

config_opts=""
manual_opts=""
runner=""
name=""

for s in ${@}; do
    if [ -z "${s##*.y*ml}" ]; then
        if [ ! -f $s ]; then
            echo $s does not exist, please check your input.
            exit 1
        fi
        config_opts="$config_opts $(parse_yaml $s)"
        runner=$(cat $s | grep -oP "runner: \K.+")
        name=$(cat $s | grep -oP "name: \K.+" || true)
        if [ -z $name ]; then
            name=$(basename "${s%.*}")
        fi
    else
        manual_opts="$manual_opts $s"
    fi
done

if [ -z $runner ]; then
    echo No runner detected, please specify a runner in the config file.
    exit 1
fi

$runner $config_opts --name $name $manual_opts
