#!/usr/bin/env python3

import os
import time
import argparse
import pandas as pd
import tempfile
from pathlib import Path
from tensorboardX import SummaryWriter

parser = argparse.ArgumentParser()
parser.add_argument("--logdir", default=".")
args = parser.parse_args()

paths = sorted(Path(".").rglob("*.csv"))
pdf = pd.DataFrame(paths, columns=["path"])
pdf["dir"] = pdf["path"].apply(lambda p: p.parent)

with tempfile.TemporaryDirectory() as tmpdir:
    writer = SummaryWriter(tmpdir)
    for name, grp in pdf.groupby("dir"):
        name = str(name)
        for path in grp["path"]:
            df = pd.read_csv(path)
            df = df.sort_values("timestamp")
            rows = df.to_dict("records")
            for row in rows:
                try:
                    step = row["step"]
                except:
                    step = None
                timestamp = row["timestamp"]
                for key in set(row) - {"timestamp", "step"}:
                    tag = "/".join([name, key])
                    try:
                        writer.add_scalar(tag, row[key], step, timestamp)
                    except:
                        pass
    os.system(f"tensorboard --logdir {tmpdir}")
